# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ReadmeGenerator < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jtarchie/readme-generator/releases/download/v0.0.1/readme-generator_darwin_arm64.tar.gz"
      sha256 "d5c07ce4fa115cb4c40b7bd7553644b541d679ce742c16b1778ff504186fca61"

      def install
        bin.install "readme-generator"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jtarchie/readme-generator/releases/download/v0.0.1/readme-generator_darwin_x86_64.tar.gz"
      sha256 "8a22059334dc03b048a2f787a80f72400168adcd838e2af698a2d7c5b61ed0c3"

      def install
        bin.install "readme-generator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtarchie/readme-generator/releases/download/v0.0.1/readme-generator_linux_arm64.tar.gz"
      sha256 "96b53ae825ad6c460c0b71910a0fa382ed796da78eb8f0d7ae2d3468ff23e8c7"

      def install
        bin.install "readme-generator"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jtarchie/readme-generator/releases/download/v0.0.1/readme-generator_linux_x86_64.tar.gz"
      sha256 "bfc7e9968443a1562c872145b7bbfa4c5960f2f4d7b2eafd09d66741a65bf27c"

      def install
        bin.install "readme-generator"
      end
    end
  end

  test do
    system "#{bin}/readme-generator --help"
  end
end
